# Generated by Django 4.2.2 on 2023-07-29 23:35

from django.db import migrations, models
import unlMaps.utils


class Migration(migrations.Migration):

    dependencies = [
        ('unlMaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque',
            name='foto',
            field=models.ImageField(blank=True, upload_to=unlMaps.utils.get_image_path),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='foto',
            field=models.ImageField(blank=True, upload_to=unlMaps.utils.get_image_path),
        ),
    ]
