# Generated by Django 4.2.2 on 2023-06-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlMaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punto',
            name='codigo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
